
export const weddingData = [
    {
        slug: "amandeep-pooja",
        title: "Amandeep & Pooja",
        story: [
            "Some love stories unfold in the most beautiful and unforgettable ways.",
            "Pooja and Amandeep’s wedding was one such celebration, where love, tradition, and heartfelt emotions came together to create a truly magical beginning.",
            "Their wedding was more than just a ceremony—it was a story of two souls coming together, surrounded by family, blessings, and the warmth of cherished traditions. Every moment of the day reflected their bond, their happiness, and the excitement of starting a new journey together.",
            "Amandeep looked regal in his elegant ivory sherwani paired with a traditional turban, carrying the grace and pride of a groom stepping into a new chapter of life. The ceremonial sword he held symbolized strength, honor, and the heritage that beautifully connects generations.",
            "Beside him stood Pooja, glowing with grace and beauty. Dressed in a richly embroidered red and gold bridal lehenga, she looked breathtaking in every sense. Her intricate jewelry, delicate makeup, and radiant smile completed the look of a bride ready to embrace a lifetime of love and happiness.",
            "One of the most touching moments of their wedding was when Pooja gently leaned beside Amandeep, sharing a quiet and emotional moment together. In that simple yet powerful gesture, their love spoke louder than words. It was a moment filled with comfort, trust, and the promise of a lifetime together.",
            "Moments like these are what make wedding photography truly special. They capture emotions that go beyond the ceremony—moments that couples will remember and cherish forever.",
            "Indian weddings are deeply rooted in tradition, and Pooja and Amandeep’s celebration beautifully honored those customs. From the elegant attire to the meaningful rituals, every detail reflected the richness of culture and the joy of family coming together.",
            "Laughter, blessings, and heartfelt smiles filled the atmosphere, making the entire celebration feel warm, vibrant, and unforgettable.",
            "As the camera captured each frame, their love story slowly unfolded through beautiful moments and genuine emotions. Every photograph became a timeless memory of the beginning of their journey together.",
            "Pooja and Amandeep’s wedding stands as a reminder that the most beautiful weddings are not just about grand celebrations, but about the love shared between two people who are ready to walk through life side by side.",
            "Their story now lives on through these photographs — a beautiful chapter of love, tradition, and the promise of forever.",
        ],
        image: [
            "https://res.cloudinary.com/dbtlo70e5/image/upload/v1772900634/0P0A9378.JPG_sigxyh.jpg",
            "https://res.cloudinary.com/dbtlo70e5/image/upload/v1772900662/IMG_4408.JPG_x7qctq.jpg",
            "https://res.cloudinary.com/dbtlo70e5/image/upload/v1772900661/IMG_4400.JPG_hjrayu.jpg",
            "https://res.cloudinary.com/dbtlo70e5/image/upload/v1772900576/0P0A9435.JPG_jehyxe.jpg",
            "https://res.cloudinary.com/dbtlo70e5/image/upload/v1772900612/0P0A9748.JPG_zbqeym.jpg",
            "https://res.cloudinary.com/dbtlo70e5/image/upload/v1772900622/0P0A9797.JPG_hoc5dv.jpg",
            "https://res.cloudinary.com/dbtlo70e5/image/upload/v1772900581/0P0A9526.JPG_esprjm.jpg",
            "https://res.cloudinary.com/dbtlo70e5/image/upload/v1772900600/0P0A9598.JPG_aggmii.jpg",
            "https://res.cloudinary.com/dbtlo70e5/image/upload/v1772900591/0P0A9589_wzzepj.jpg",
            "https://res.cloudinary.com/dbtlo70e5/image/upload/v1772900617/0P0A9711.JPG_lwd9lb.jpg",
            "https://res.cloudinary.com/dbtlo70e5/image/upload/v1772900601/0P0A9626.JPG_ds0jci.jpg",
            "https://res.cloudinary.com/dbtlo70e5/image/upload/v1772900640/0P0A9892.JPG_vptpvj.jpg",
            "https://res.cloudinary.com/dbtlo70e5/image/upload/v1772900610/0P0A9703.JPG_tmctit.jpg",
            "https://res.cloudinary.com/dbtlo70e5/image/upload/v1772900602/0P0A0516.JPG_gddrm7.jpg",
            "https://res.cloudinary.com/dbtlo70e5/image/upload/v1772900601/0P0A0490.JPG_ucgkvk.jpg",
            "https://res.cloudinary.com/dbtlo70e5/image/upload/v1772900595/0P0A0509.JPG_wtgqu2.jpg ",
            "https://res.cloudinary.com/dbtlo70e5/image/upload/v1772900589/0P0A0475.JPG_ttvjwm.jpg",
            "https://res.cloudinary.com/dbtlo70e5/image/upload/v1772900575/0P0A0033.JPG_a25i5o.jpg",
            "https://res.cloudinary.com/dbtlo70e5/image/upload/v1772900632/0P0A9971.JPG_gz1i0i.jpg",
            "https://res.cloudinary.com/dbtlo70e5/image/upload/v1772900576/0P0A0096.JPG_mllswt.jpg",
            "https://res.cloudinary.com/dbtlo70e5/image/upload/v1772900642/0P0A9392.JPG_lgxxot.jpg",
            "https://res.cloudinary.com/dbtlo70e5/image/upload/v1772900613/0P0A9756.JPG_im87u7.jpg",


        ]
    },
    {
        slug: "taranveer-bhupinder",
        title: "Taranveer Singh & Bhupinder Kaur",
        story: [
            "Some love stories are not just told — they are beautifully felt in every moment.", 
            "Taranveer Singh and Bhupinder Kaur’s wedding was one such story, where tradition, elegance, and heartfelt emotions came together to create a celebration that will be remembered forever.",
            "From the very first glance they shared, it was clear that their bond was something truly special. Their wedding shoot unfolded like a timeless narrative, capturing the quiet smiles, the joyful laughter, and the deep connection between two souls ready to begin their journey together.",
            "Taranveer Singh looked regal in his ivory sherwani paired with a vibrant red turban and ceremonial sword, a look that perfectly reflected the pride and heritage of a Sikh groom. His presence carried confidence, warmth, and a sense of tradition that added a royal charm to the celebration.",
            "Beside him stood Bhupinder Kaur, glowing with grace and elegance. Adorned in a beautifully embroidered red bridal lehenga, complemented by exquisite jewelry and delicate bridal details, she embodied the beauty of a timeless bride. Every step she took reflected confidence, joy, and the excitement of stepping into a new chapter of life.",
            "Together, they created moments that felt effortless yet unforgettable. Whether it was the way they held hands, shared smiles, or looked at each other with warmth, every frame told a story of love that felt genuine and deeply personal.",
            "Set against elegant surroundings, their wedding shoot became a visual story of their journey — a blend of romance, tradition, and celebration. The natural chemistry between them brought life to every photograph, turning simple moments into lasting memories.",
            "As the camera captured these precious moments, their love revealed itself in the smallest details — a gentle smile, a proud glance, a shared laugh. These were the moments that truly defined their wedding day.",
            "Taranveer Singh and Bhupinder Kaur’s wedding was not just a celebration of two people coming together, but the beginning of a beautiful journey filled with dreams, love, and endless possibilities.",
            "Their story now lives forever through these photographs — a timeless reminder that the most beautiful weddings are the ones where love shines in its purest form.",
        ],
        image: [
            "https://res.cloudinary.com/dbtlo70e5/image/upload/v1772900655/042A6099.JPG_sghxnt.jpg",
            "https://res.cloudinary.com/dbtlo70e5/image/upload/v1772900650/042A6075.JPG_r5v9qv.jpg",
            "https://res.cloudinary.com/dbtlo70e5/image/upload/v1772900655/042A6091.JPG_kunnne.jpg",
            "https://res.cloudinary.com/dbtlo70e5/image/upload/v1772900658/042A6479_axpyoc.jpg",
            "https://res.cloudinary.com/dbtlo70e5/image/upload/v1772900666/ISCO6424_ypmdhn.jpg ",
            "https://res.cloudinary.com/dbtlo70e5/image/upload/v1772900667/ISCO6437_efzbyt.jpg",
            "https://res.cloudinary.com/dbtlo70e5/image/upload/v1772900655/042A6091.JPG_kunnne.jpg",
            "https://res.cloudinary.com/dbtlo70e5/image/upload/v1772900649/042A6064.JPG_1_mh5iy3.jpg",
            "https://res.cloudinary.com/dbtlo70e5/image/upload/v1772900639/042A6038.JPG_nif0uy.jpg",
            "https://res.cloudinary.com/dbtlo70e5/image/upload/v1772377731/042A6080_omnzdk.jpg",
            "https://res.cloudinary.com/dbtlo70e5/image/upload/v1772900645/042A6055.JPG_r7rrpu.jpg",
            "https://res.cloudinary.com/dbtlo70e5/image/upload/v1772900648/042A6078_ydgftc.jpg",
            "https://res.cloudinary.com/dbtlo70e5/image/upload/v1772377750/042A6559_lg2akd.jpg",
            "https://res.cloudinary.com/dbtlo70e5/image/upload/v1772377745/042A6463_n4pbpv.jpg",
            "https://res.cloudinary.com/dbtlo70e5/image/upload/v1772377733/042A6082_ih0wyi.jpg",
            "https://res.cloudinary.com/dbtlo70e5/image/upload/v1772377749/042A6563_fzipdy.jpg",
            "https://res.cloudinary.com/dbtlo70e5/image/upload/v1772377733/042A6077_cgmise.jpg",
            "https://res.cloudinary.com/dbtlo70e5/image/upload/v1772377739/042A6470_a4s7wc.jpg",
        ]
    },
];
